dv:
  source:
    # _type: mongodb
    # auth:
    #   _type: explicit
    #   host: cluster0.qw3lamc.mongodb.net
    #   password: ILVKTjnxYvYOd2xX
    #   username: danielbaquini_db_user
    # data:
    #   audience:
    #     database: experimentacao
    #     collection: audience
    #   requests:
    #     database: experimentacao
    #     collection: requests
    #   rules:
    #     database: experimentacao
    #     collection: rules
    _type: catalog
    auth:
      _type: explicit
    data:
      audience:
        data_layer: ucs_db
        data_name: audience
      requests:
        data_layer: ucs_db
        data_name: requests
      rules:
        data_layer: ucs_db
        data_name: rules
  target:
    _type: mongodb
    auth:
      _type: explicit
      host: cluster0.qw3lamc.mongodb.net
      password: ILVKTjnxYvYOd2xX
      username: danielbaquini_db_user
    data:
      audience:
        database: experimentacao
        collection: audience
      requests:
        database: experimentacao
        collection: requests
      rules:
        database: experimentacao
        collection: rules

ho:

pr: